apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: bloomingteratoma/api:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          ports:
            - containerPort: 7001

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
