apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bloomingteratoma/auth:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          # resources:      
          #   limits:
          #     memory: "1Gi"
          #     cpu: "0.5" 
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
