apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-configmap
data:
  # AWS S3 Config
  AWS_S3_REGION: ap-southeast-1
  AWS_S3_BUCKET: cloudcheck-bucket
  QUEUE_URL: https://sqs.ap-southeast-1.amazonaws.com/427326701664/cloudcheck-image-upload
  # FrontEnd
  FRONTEND_APP_URL: http://localhost:3000
  ENVOY_URL: http://localhost:8080

  NEXT_PUBLIC_AWS_S3_REGION: ap-southeast-1
  NEXT_PUBLIC_AWS_S3_BUCKET: cloudcheck-bucket
  NEXT_PUBLIC_QUEUE_URL: https://sqs.ap-southeast-1.amazonaws.com/427326701664/cloudcheck-image-upload
  NEXT_PUBLIC_ENVOY_URL: http://localhost:8080
  NEXT_PUBLIC_AUTH_URL: http://localhost:8080/auth
  NEXT_PUBLIC_AWS_S3_URL: http://localhost:8080/s3-service
  NEXT_PUBLIC_IMAGE_CLASSIFIER_URL: http://localhost:8080/fl-service
  NEXT_PUBLIC_FRONTEND_APP_URL: http://localhost:3000
  NEXT_PUBLIC_DEMO_MODE: "true"