apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
spec:
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: bloomingteratoma/envoy:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9901
          # resources:      
          #   limits:
          #     memory: "1Gi"
          #     cpu: "0.5" 

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  type: LoadBalancer
  selector:
    app: envoy
  ports:
    - name: port-ingress
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: port-egress
      port: 9901
      targetPort: 9901
      protocol: TCP
