apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-learning-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: federated-learning
  template:
    metadata:
      labels:
        app: federated-learning
    spec:
      containers:
        - name: federated-learning
          image: bloomingteratoma/federated-learning:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          # resources:      
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1" 
          ports:
            - containerPort: 6002

---
apiVersion: v1
kind: Service
metadata:
  name: federated-learning-service
spec:
  type: LoadBalancer
  selector:
    app: federated-learning
  ports:
    - port: 6002
      targetPort: 6002
      protocol: TCP
